name: APIM VNet Deployment

on:
  push:
    branches: [main]
    paths: ['**.tf', '.github/workflows/deploy.yml']
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action'
        required: true
        default: 'plan'
        type: choice
        options: [plan, apply, destroy]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: mmuyideen/terraform-modules-and-pipelines/.github/workflows/terraform-ci.yml@main
    with:
      cloud_provider: azure
      action: ${{ inputs.action || 'plan' }}
      var_file: -var-file=terraform.tfvars
      # backend_config: |
      #   -backend-config=resource_group_name=terraform-backend-rg 
      #   -backend-config=storage_account_name=deenterraformstate 
      #   -backend-config=container_name=tfstate 
      #   -backend-config=key=apim-vnet-terraform.tfstate
    secrets: inherit
